package org.psint.beyosclothing.core.security;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

/**
 * Peppered Password Encoder
 *
 * Wraps BCrypt with a secret pepper value loaded from application config (NOT stored in DB).
 *
 * How it works:
 *   encode(rawPassword)   → BCrypt.encode(rawPassword + pepper)
 *   matches(raw, encoded) → BCrypt.matches(raw + pepper, encoded)
 *
 * Why this prevents direct DB manipulation:
 *   - Any hash generated by an external BCrypt tool (bcrypt.online, etc.) will NOT include
 *     the pepper, so it will NEVER match during authentication.
 *   - Even with full database read access, an attacker cannot produce a valid password hash
 *     without knowing the pepper secret stored only in application configuration.
 *
 * IMPORTANT: The pepper value must NEVER be stored in or derived from the database.
 *            It must be set via environment variable in production.
 */
public class PepperedPasswordEncoder implements PasswordEncoder {

    private final BCryptPasswordEncoder bcrypt;
    private final String pepper;

    public PepperedPasswordEncoder(String pepper) {
        this.bcrypt = new BCryptPasswordEncoder(12); // strength 12 ≈ 1 second on modern hardware
        this.pepper = pepper;
    }

    @Override
    public String encode(CharSequence rawPassword) {
        return bcrypt.encode(rawPassword.toString() + pepper);
    }

    @Override
    public boolean matches(CharSequence rawPassword, String encodedPassword) {
        return bcrypt.matches(rawPassword.toString() + pepper, encodedPassword);
    }

    @Override
    public boolean upgradeEncoding(String encodedPassword) {
        return bcrypt.upgradeEncoding(encodedPassword);
    }
}

